# Generated by Django 6.1.1 on 2026-09-21 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('extra_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='shop.product')),
            ],
            options={
                'verbose_name': 'Product addon',
                'verbose_name_plural': 'Product addons',
                'constraints': [models.UniqueConstraint(fields=('product', 'name'), name='unique_product_addon')],
            },
        ),
    ]
