# Generated by Django 6.1.1 on 2026-09-23 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_payment_status'),
        ('shop', '0009_alter_category_name_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_user_product_review',
        ),
        migrations.AddField(
            model_name='review',
            name='order_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review', to='orders.orderitem', verbose_name='Позиция заказа'),
        ),
    ]
