# Generated by Django 6.1.1 on 2026-09-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_method_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_snapshot',
            field=models.JSONField(blank=True, default=list, editable=False, verbose_name='Содержимое корзины при оформлении'),
        ),
    ]
