# Generated by Django 6.1.1 on 2026-09-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_cart_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('demo_card', 'Картой онлайн'), ('cash', 'При получении')], default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
