# Generated by Django 6.1.1 on 2026-09-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('failed', 'Ошибка оплаты'), ('cancelled', 'Оплата отменена'), ('refunded', 'Возврат совершен')], default='pending', max_length=20, verbose_name='Статус оплаты'),
        ),
    ]
